# <component>
name: train_prep_heart_disease
display_name: Train heart disease model
type: command
inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  mlflow_experiment_name:
    type: string
  registered_model_name:
    type: string
  owner:
    type: string
  project:
    type: string
  business_unit:
    type: string
code: .
environment:
  azureml://registries/azureml/environments/sklearn-1.0/labels/latest
command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --mlflow_experiment_name ${{inputs.mlflow_experiment_name}}
  --registered_model_name ${{inputs.registered_model_name}}
  --owner ${{inputs.owner}}
  --project ${{inputs.project}}
  --business_unit ${{inputs.business_unit}}
# </component>
