name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pip=21.2.4
  - scikit-learn=1.2.2
  - pandas=2.0.2
  - mlfow=2.4.1
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - xgboost==2.0.3
    - azureml-mlflow==1.42.0
